### ISSUE TITLE
Concentration value not truncated before looking up breakpoints.

### ISSUE THREAD

**Issue by Leftium** [RiANOl/aqi-us#3]
**Repro:** https://runkit.com/embed/ttj0vs14n121 
```
var aqi = require("aqi-us")
pm25_aqi = aqi.pm25(12.06); // NaN
```
**Expected Result:**
50

**Actual Result:** 
NaN

---

Notes:

Concentrations should be truncated depending on the pollutant:
- Ozone (ppm) – truncate to 3 decimal places
- PM2.5 (µg/m3) – truncate to 1 decimal place
- PM10 (µg/m3) – truncate to integer
- CO (ppm) – truncate to 1 decimal place
- SO2 (ppb) – truncate to integer
- NO2 (ppb) – truncate to integer

 source: https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf

**Comment by RiANOl** [comment]
Fixed by bf5f5f33c604b8328da904756ebeadc5af4914ca
